### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [rosenpin/Screenshot-Sharer#3]
Hi @rosenpin 

I found [this app](https://play.google.com/store/apps/details?id=co.Aqua.screenshotsharer) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your app and a link to this repo.

**Comment by rosenpin** [comment]
Thank you very much for informing me about this issue, I will submit a request to Google

**Comment by vijai1996** [comment]
He seem to be a repeated offender. I just reported one of his app which is a copy of my app. I still see copy of your app is not removed from play. May I know the outcome?

**Comment by Poussinou** [comment]
It IS a repeatd offender, all his apps are copies of open-source apps

**Comment by rosenpin** [comment]
@vijai1996 
Seems like it isn't Google's top priority

**Comment by vijai1996** [comment]
Damn...  Thats saddening! I will keep mailing and nagging Google until they do. Because, this is my ONLY top priority ;)

**Comment by Poussinou** [comment]
The app has been removed. Please report here if you find other copies 👍
