### ISSUE TITLE
Files being saved without an extension

### ISSUE THREAD

**Issue by MateusAuri** [rosenpin/Screenshot-Sharer#9]
I don't know if it's just on my end, but whenever I capture a screenshot, it gets saved without an extension.
This makes it unusable (both unopenable and unshareable) until I manually open a file explorer app and rename the file to append ".jpg".

Oh, and I'm on android 6.0, using Sharedr as the share menu. I just installed your app through F-Droid.

BTW, nice app. My phone's buttons are messed up, and I needed an assistant app that saves screenshots instead of just sharing them.

**Comment by rosenpin** [comment]
Weird, definitely doesn't happen to me

It might have been broken in my last update that added support for Android Q. Maybe it only works for Q now :P

**Comment by MateusAuri** [comment]
Then maybe it's on my end. 🤔 
I'll try checking whatever I can to see if I find what's causing it. Unfortunately, I don't have another device to test it on right now, though.

**Comment by ghost** [comment]
I just installed Screenshot Sharer v1.9 from F-Droid on Android 6.0 - same issue.

> It might have been broken in my last update that added support for Android Q. Maybe it only works for Q now

@rosenpin, Why just not add `.png` to write after `screenshot-$time` in the saved file names?
